package.json
src/index.js
src/models/user.model.js
src/routes/user.routes.js
src/storages/user.storage.js

Create a first user model for next works. This PR closes #2 .

User model

---

.github/workflows/test.yml
README.md
package-lock.json
package.json
src/index.js
src/middlewares/auth.js
src/models/location.model.js
src/models/user.model.js
src/routes/forecasts.routes.js
src/storages/location.storage.js
src/storages/openweathermap.storage.js
src/storages/storage.utils.js
src/storages/troposhpere.storage.js
src/storages/weatherProvider.js
test/forecasts.test.js
test/storages/locationStorage.test.js
test/storages/storage.utils.test.js
test/storages/weatherProvider.test.js

Remove old code of methods unused, improve unit testing and resolve some bug with axios error managing.

Troposphere call

---

.github/workflows/test.yml
src/config/config.js
src/routes/forecasts.routes.js
src/storages/openweathermap.storage.js
src/storages/storage.utils.js
src/storages/troposhpere.storage.js
src/storages/weatherProvider.js
test/forecasts.test.js
test/storages/weatherProvider.test.js

Troposphere call 2

---

.dockerignore
.github/workflows/deploy.yml
Dockerfile
README.md

Create the Dockerfile and explain how to use it.

Docker init

---

.github/workflows/deploy.yml

Create deploy workflow.

---

Dockerfile
src/index.js

Expose to docker port defined in env vars.

---

package-lock.json
package.json
src/config/config.js
src/config/nodemailer.config.js
src/index.js
src/models/user.model.js
src/routes/auth.routes.js
src/services/auth.service.js
src/storages/auth.storage.js
test/aut.test.js
test/auth.test.js

ps: i test ancora da finire di fare in cartella test, sono commentati

Confermation email corretto

---

.github/workflows/test.yml
README.md
package-lock.json
package.json
src/controllers/forecast.controller.js
src/controllers/station.controller.js
src/index.js
src/models/station.model.js
src/models/user.model.js
src/routes/forecasts.routes.js
src/routes/station.routes.js
src/storages/station.storage.js
test/forecasts.test.js
test/stations.test.js
test/storages/locationStorage.test.js

Add Api to support local weather stations and their registration per user.

Iot weather integration

---

.github/workflows/deploy.yml
package.json

Prepare repository for release 0.3.0. Merge after #34 .

Prepare release 0.3.0

---

.github/workflows/deploy.yml

This pull request will fix some issues resolved in iot-weather repository about the deploy of the container to docker hub repositories, especially about images tags.

Copy bug fixes from iot-weather.

---

src/index.js
test/storages/authTest.test.js

cambiamento nome api in auth @Daniele-Tentoni @igor-lirussi con annessa pr sul client

refactor api in auth

---

src/controllers/feedback.controller.js
src/index.js
src/models/feedback.model.js
src/models/provider.model.js
src/routes/feedbacks.routes.js
src/storages/feedback.storage.js
test/feedbacks.test.js
test/forecasts.test.js
test/storages/feedback.storage.test.js
test/utils/user.utils.js

New feedbacks routes for the server. Now you can create, delete feedbacks and get them by provider or from all providers. Closes #39 .

Feedback routes

---

README.md
package-lock.json
src/controllers/feedback.controller.js
src/index.js
src/models/provider.model.js
src/routes/feedbacks.routes.js
src/storages/feedback.storage.js
test/feedbacks.test.js
test/storages/feedback.storage.test.js

Provvedo a generare un nuovo test per controllare di generare correttamente i providers di base all'avvio del server. Nel caso in cui essi già ci siano, allora segnala solo un warning ma non si pianta, proseguendo con l'esecuzione.

Providers generation fix

---

package.json

Pull request per incrementare il numero di versione dell'applicativo.

Increment version to 0.5.0

---

src/controllers/forecast.controller.js
src/routes/user.routes.js
src/storages/openweathermap.storage.js
src/storages/troposhpere.storage.js
test/forecasts.test.js

Mi sono accorto che l'orario delle previsioni prelevate nelle richieste di previsioni per più giorni differivano da un provider all'altro, questa pr risolve questo problema.

Fix hours synchronization between providers.

---

src/controllers/user.controller.js
src/models/feedback.model.js
src/storages/user.storage.js
test/feedbacks.test.js
test/storages/feedback.storage.test.js
test/users.test.js
test/utils/feedback.utils.js

Crea la route per ottenere i feedbacks di uno specifico utente. Crea i test annessi. Segue la seconda convenzione specificata nel [mio commento](https://github.com/Weather-Vortex/weather-vortex-server/issues/59#issuecomment-914436932). Closes #59 .

Feedback per user

---

src/storages/auth.storage.js

@Daniele-Tentoni 
Prima approvare questo sul server e poi approvare quello sul client

aggiunto id in logged_in

---

src/controllers/user.controller.js
src/models/station.model.js
src/models/user.model.js
src/routes/user.routes.js
src/storages/user.storage.js
test/users.test.js
test/utils/user.utils.js

Crea la route per ottenere le stazioni per utente. Closes #60 . Resolve #60 .

Get Stations per user

---

src/controllers/feedback.controller.js
src/controllers/forecast.controller.js
src/controllers/station.controller.js
src/index.js
src/models/station.model.js
src/routes/feedbacks.routes.js
src/routes/forecasts.routes.js
src/routes/station.routes.js
src/storages/data/conditionCodes.js
src/storages/feedback.storage.js
src/storages/openweathermap.storage.js
src/storages/station.storage.js
src/storages/stationProvider.storage.js
src/storages/troposhpere.storage.js
src/storages/weatherProvider.js
test/feedbacks.test.js
test/stations.test.js
test/storages/feedback.storage.test.js
test/storages/weatherProvider.test.js
test/users.test.js

Implementa le previsioni per più giorni, sia in rest che in socket e funziona con il client alla relativa pull request.
Alla richiesta di previsioni, cerca se ci sono stazioni con la località assegnata ed invia anche quelle previsioni, solamente per le `current` però, dato che non sarebbero abbastanza potenti forse per fare previsioni meteo solamente con i dati a loro disposizione e la loro potenza computazionale.
Closes #61 .

Weather from stations

---

package.json

Increment version number before next release.

Increment version number.

---

.github/workflows/cronjob.yml
.github/workflows/test.yml
src/config/nodemailer.config.js
src/controllers/forecast.controller.js
src/models/user.model.js
src/routes/forecasts.routes.js
src/storages/user.storage.js
test/forecasts.test.js
test/utils/user.utils.js

Create a new route in forecast router and trigger email sending at 7 am Italy time. Add a new unit test.

Email trigger

---

README.md
package.json
src/index.js
test/index.test.js

Add email notification for any user that have a preferred location. Trigger a job each morning to send those notifications. Add their tests. Closes #12, #60, #61 and #64.

Prepare release 0.7.0

---

.github/workflows/cronjob.yml
package.json
src/controllers/forecast.controller.js
src/storages/storage.utils.js
src/storages/troposhpere.storage.js
src/storages/weatherProvider.js
test/forecasts.test.js
test/storages/locationStorage.test.js
test/storages/weatherProvider.test.js

Add many tests to location storage and weather providers and fix the bug of missing provider crash system.

Provider blocking failure

---

src/config/nodemailer.config.js
src/storages/auth.storage.js

Send the right verification link with given return link. See related issue on client.

Link refactoring

---

src/storages/location.storage.js
src/storages/openweathermap.storage.js
test/forecasts.test.js
test/storages/locationStorage.test.js
test/utils/location.utils.js

Fix the "London Bug". New unit test created with a real world location to fetch.

London bug

---

README.md
package-lock.json
package.json
src/config/nodemailer.config.js
src/models/user.model.js
src/routes/auth.routes.js
src/storages/auth.storage.js
test/storages/authTest.test.js
test/utils/user.utils.js

Prepare the release 1.0.0 of the server application. This will be our public interface for the exam.

Release 1.0.0
